title: Mosiur Rahman
description: Jr. Full Stack Web Developer, Science Master Ltd.
baseurl: "/remple/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "mosiur.n00b@gmail.com"
linkedin: "http://linkedin.com/in/mosiur-n00b"
github: "https://github.com/mosiur-n00b"
medium: "https://medium.com/@mosiur.n00b"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
